# Generated by Django 2.1.3 on 2019-02-26 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='a group', max_length=32)),
            ],
            options={
                'verbose_name': '用户组',
                'verbose_name_plural': '用户组',
                'db_table': 'my_user_group',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='people', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('1', '普通用户'), ('2', '会员用户'), ('3', 'VIP用户')], max_length=32)),
                ('user_name', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('token', models.CharField(default='123', max_length=64)),
                ('address', models.CharField(default='address', max_length=64)),
                ('phone_number', models.IntegerField(default=123456)),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='index.MyUserGroup')),
                ('user', models.ManyToManyField(default=1, to='index.Role')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('user', models.OneToOneField(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='index.UserInfo')),
            ],
        ),
    ]
