# Generated by Django 2.1.3 on 2019-02-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20190226_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user',
            new_name='role',
        ),
    ]
